/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as AuthedVedlikeholdRouteImport } from './routes/_authed/vedlikehold'
import { Route as AuthedUtleggRouteImport } from './routes/_authed/utlegg'
import { Route as AuthedUsersettingsRouteImport } from './routes/_authed/usersettings'
import { Route as AuthedTodosRouteImport } from './routes/_authed/todos'
import { Route as AuthedShoppinglistRouteImport } from './routes/_authed/shoppinglist'
import { Route as AuthedSettlementRouteImport } from './routes/_authed/settlement'
import { Route as AuthedPlanstayRouteImport } from './routes/_authed/planstay'
import { Route as AuthedPlanleggoppholdRouteImport } from './routes/_authed/planleggopphold'
import { Route as AuthedOversiktRouteImport } from './routes/_authed/oversikt'
import { Route as AuthedOppgjorRouteImport } from './routes/_authed/oppgjor'
import { Route as AuthedOppgaverRouteImport } from './routes/_authed/oppgaver'
import { Route as AuthedManagepropertyRouteImport } from './routes/_authed/manageproperty'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedInnstillingerRouteImport } from './routes/_authed/innstillinger'
import { Route as AuthedHandlelisteRouteImport } from './routes/_authed/handleliste'
import { Route as AuthedExpensesRouteImport } from './routes/_authed/expenses'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdministrerRouteImport } from './routes/_authed/administrer'
import { Route as AuthedManagepropertyIndexRouteImport } from './routes/_authed/manageproperty/index'
import { Route as AuthedAdministrerIndexRouteImport } from './routes/_authed/administrer/index'
import { Route as AuthedManagepropertyUsersRouteImport } from './routes/_authed/manageproperty/users'
import { Route as AuthedManagepropertyUsergroupsRouteImport } from './routes/_authed/manageproperty/usergroups'
import { Route as AuthedManagepropertyStructuresRouteImport } from './routes/_authed/manageproperty/structures'
import { Route as AuthedManagepropertySplitPolicyRouteImport } from './routes/_authed/manageproperty/split-policy'
import { Route as AuthedManagepropertySettingsRouteImport } from './routes/_authed/manageproperty/settings'
import { Route as AuthedManagepropertyPriorityRouteImport } from './routes/_authed/manageproperty/priority'
import { Route as AuthedManagepropertyOwnershipRouteImport } from './routes/_authed/manageproperty/ownership'
import { Route as AuthedManagepropertyInvitesRouteImport } from './routes/_authed/manageproperty/invites'
import { Route as AuthedManagepropertyInfrastructureRouteImport } from './routes/_authed/manageproperty/infrastructure'
import { Route as AuthedManagepropertyInfoRouteImport } from './routes/_authed/manageproperty/info'
import { Route as AuthedManagepropertyEquipmentRouteImport } from './routes/_authed/manageproperty/equipment'
import { Route as AuthedManagepropertyContactsRouteImport } from './routes/_authed/manageproperty/contacts'
import { Route as AuthedAdministrerUtstyrRouteImport } from './routes/_authed/administrer/utstyr'
import { Route as AuthedAdministrerUtgiftskategorierRouteImport } from './routes/_authed/administrer/utgiftskategorier'
import { Route as AuthedAdministrerPrioritetRouteImport } from './routes/_authed/administrer/prioritet'
import { Route as AuthedAdministrerKontakterRouteImport } from './routes/_authed/administrer/kontakter'
import { Route as AuthedAdministrerInvitasjonerRouteImport } from './routes/_authed/administrer/invitasjoner'
import { Route as AuthedAdministrerInnstillingerRouteImport } from './routes/_authed/administrer/innstillinger'
import { Route as AuthedAdministrerInfrastrukturRouteImport } from './routes/_authed/administrer/infrastruktur'
import { Route as AuthedAdministrerInfoRouteImport } from './routes/_authed/administrer/info'
import { Route as AuthedAdministrerFordelingspolicyRouteImport } from './routes/_authed/administrer/fordelingspolicy'
import { Route as AuthedAdministrerEierskapRouteImport } from './routes/_authed/administrer/eierskap'
import { Route as AuthedAdministrerBygningerRouteImport } from './routes/_authed/administrer/bygninger'
import { Route as AuthedAdministrerBrukergrupperRouteImport } from './routes/_authed/administrer/brukergrupper'
import { Route as AuthedAdministrerBrukereRouteImport } from './routes/_authed/administrer/brukere'
import { Route as AuthedAdministrerFordelingspolicyIndexRouteImport } from './routes/_authed/administrer/fordelingspolicy/index'
import { Route as AuthedAdministrerFordelingspolicyPersondaysRouteImport } from './routes/_authed/administrer/fordelingspolicy/persondays'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedVedlikeholdRoute = AuthedVedlikeholdRouteImport.update({
  id: '/vedlikehold',
  path: '/vedlikehold',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUtleggRoute = AuthedUtleggRouteImport.update({
  id: '/utlegg',
  path: '/utlegg',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersettingsRoute = AuthedUsersettingsRouteImport.update({
  id: '/usersettings',
  path: '/usersettings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodosRoute = AuthedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShoppinglistRoute = AuthedShoppinglistRouteImport.update({
  id: '/shoppinglist',
  path: '/shoppinglist',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettlementRoute = AuthedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanstayRoute = AuthedPlanstayRouteImport.update({
  id: '/planstay',
  path: '/planstay',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanleggoppholdRoute = AuthedPlanleggoppholdRouteImport.update({
  id: '/planleggopphold',
  path: '/planleggopphold',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOversiktRoute = AuthedOversiktRouteImport.update({
  id: '/oversikt',
  path: '/oversikt',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOppgjorRoute = AuthedOppgjorRouteImport.update({
  id: '/oppgjor',
  path: '/oppgjor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOppgaverRoute = AuthedOppgaverRouteImport.update({
  id: '/oppgaver',
  path: '/oppgaver',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagepropertyRoute = AuthedManagepropertyRouteImport.update({
  id: '/manageproperty',
  path: '/manageproperty',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInnstillingerRoute = AuthedInnstillingerRouteImport.update({
  id: '/innstillinger',
  path: '/innstillinger',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHandlelisteRoute = AuthedHandlelisteRouteImport.update({
  id: '/handleliste',
  path: '/handleliste',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExpensesRoute = AuthedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdministrerRoute = AuthedAdministrerRouteImport.update({
  id: '/administrer',
  path: '/administrer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagepropertyIndexRoute =
  AuthedManagepropertyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedAdministrerIndexRoute = AuthedAdministrerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedManagepropertyUsersRoute =
  AuthedManagepropertyUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyUsergroupsRoute =
  AuthedManagepropertyUsergroupsRouteImport.update({
    id: '/usergroups',
    path: '/usergroups',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyStructuresRoute =
  AuthedManagepropertyStructuresRouteImport.update({
    id: '/structures',
    path: '/structures',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertySplitPolicyRoute =
  AuthedManagepropertySplitPolicyRouteImport.update({
    id: '/split-policy',
    path: '/split-policy',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertySettingsRoute =
  AuthedManagepropertySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyPriorityRoute =
  AuthedManagepropertyPriorityRouteImport.update({
    id: '/priority',
    path: '/priority',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyOwnershipRoute =
  AuthedManagepropertyOwnershipRouteImport.update({
    id: '/ownership',
    path: '/ownership',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyInvitesRoute =
  AuthedManagepropertyInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyInfrastructureRoute =
  AuthedManagepropertyInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyInfoRoute =
  AuthedManagepropertyInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyEquipmentRoute =
  AuthedManagepropertyEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedManagepropertyContactsRoute =
  AuthedManagepropertyContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthedManagepropertyRoute,
  } as any)
const AuthedAdministrerUtstyrRoute = AuthedAdministrerUtstyrRouteImport.update({
  id: '/utstyr',
  path: '/utstyr',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedAdministrerUtgiftskategorierRoute =
  AuthedAdministrerUtgiftskategorierRouteImport.update({
    id: '/utgiftskategorier',
    path: '/utgiftskategorier',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerPrioritetRoute =
  AuthedAdministrerPrioritetRouteImport.update({
    id: '/prioritet',
    path: '/prioritet',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerKontakterRoute =
  AuthedAdministrerKontakterRouteImport.update({
    id: '/kontakter',
    path: '/kontakter',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInvitasjonerRoute =
  AuthedAdministrerInvitasjonerRouteImport.update({
    id: '/invitasjoner',
    path: '/invitasjoner',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInnstillingerRoute =
  AuthedAdministrerInnstillingerRouteImport.update({
    id: '/innstillinger',
    path: '/innstillinger',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInfrastrukturRoute =
  AuthedAdministrerInfrastrukturRouteImport.update({
    id: '/infrastruktur',
    path: '/infrastruktur',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInfoRoute = AuthedAdministrerInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedAdministrerFordelingspolicyRoute =
  AuthedAdministrerFordelingspolicyRouteImport.update({
    id: '/fordelingspolicy',
    path: '/fordelingspolicy',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerEierskapRoute =
  AuthedAdministrerEierskapRouteImport.update({
    id: '/eierskap',
    path: '/eierskap',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBygningerRoute =
  AuthedAdministrerBygningerRouteImport.update({
    id: '/bygninger',
    path: '/bygninger',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBrukergrupperRoute =
  AuthedAdministrerBrukergrupperRouteImport.update({
    id: '/brukergrupper',
    path: '/brukergrupper',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBrukereRoute =
  AuthedAdministrerBrukereRouteImport.update({
    id: '/brukere',
    path: '/brukere',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerFordelingspolicyIndexRoute =
  AuthedAdministrerFordelingspolicyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdministrerFordelingspolicyRoute,
  } as any)
const AuthedAdministrerFordelingspolicyPersondaysRoute =
  AuthedAdministrerFordelingspolicyPersondaysRouteImport.update({
    id: '/persondays',
    path: '/persondays',
    getParentRoute: () => AuthedAdministrerFordelingspolicyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/administrer': typeof AuthedAdministrerRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/expenses': typeof AuthedExpensesRoute
  '/handleliste': typeof AuthedHandlelisteRoute
  '/innstillinger': typeof AuthedInnstillingerRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/manageproperty': typeof AuthedManagepropertyRouteWithChildren
  '/oppgaver': typeof AuthedOppgaverRoute
  '/oppgjor': typeof AuthedOppgjorRoute
  '/oversikt': typeof AuthedOversiktRoute
  '/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/planstay': typeof AuthedPlanstayRoute
  '/settlement': typeof AuthedSettlementRoute
  '/shoppinglist': typeof AuthedShoppinglistRoute
  '/todos': typeof AuthedTodosRoute
  '/usersettings': typeof AuthedUsersettingsRoute
  '/utlegg': typeof AuthedUtleggRoute
  '/vedlikehold': typeof AuthedVedlikeholdRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  '/administrer/info': typeof AuthedAdministrerInfoRoute
  '/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/manageproperty/contacts': typeof AuthedManagepropertyContactsRoute
  '/manageproperty/equipment': typeof AuthedManagepropertyEquipmentRoute
  '/manageproperty/info': typeof AuthedManagepropertyInfoRoute
  '/manageproperty/infrastructure': typeof AuthedManagepropertyInfrastructureRoute
  '/manageproperty/invites': typeof AuthedManagepropertyInvitesRoute
  '/manageproperty/ownership': typeof AuthedManagepropertyOwnershipRoute
  '/manageproperty/priority': typeof AuthedManagepropertyPriorityRoute
  '/manageproperty/settings': typeof AuthedManagepropertySettingsRoute
  '/manageproperty/split-policy': typeof AuthedManagepropertySplitPolicyRoute
  '/manageproperty/structures': typeof AuthedManagepropertyStructuresRoute
  '/manageproperty/usergroups': typeof AuthedManagepropertyUsergroupsRoute
  '/manageproperty/users': typeof AuthedManagepropertyUsersRoute
  '/administrer/': typeof AuthedAdministrerIndexRoute
  '/manageproperty/': typeof AuthedManagepropertyIndexRoute
  '/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/administrer/fordelingspolicy/': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/expenses': typeof AuthedExpensesRoute
  '/handleliste': typeof AuthedHandlelisteRoute
  '/innstillinger': typeof AuthedInnstillingerRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/oppgaver': typeof AuthedOppgaverRoute
  '/oppgjor': typeof AuthedOppgjorRoute
  '/oversikt': typeof AuthedOversiktRoute
  '/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/planstay': typeof AuthedPlanstayRoute
  '/settlement': typeof AuthedSettlementRoute
  '/shoppinglist': typeof AuthedShoppinglistRoute
  '/todos': typeof AuthedTodosRoute
  '/usersettings': typeof AuthedUsersettingsRoute
  '/utlegg': typeof AuthedUtleggRoute
  '/vedlikehold': typeof AuthedVedlikeholdRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/administrer/info': typeof AuthedAdministrerInfoRoute
  '/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/manageproperty/contacts': typeof AuthedManagepropertyContactsRoute
  '/manageproperty/equipment': typeof AuthedManagepropertyEquipmentRoute
  '/manageproperty/info': typeof AuthedManagepropertyInfoRoute
  '/manageproperty/infrastructure': typeof AuthedManagepropertyInfrastructureRoute
  '/manageproperty/invites': typeof AuthedManagepropertyInvitesRoute
  '/manageproperty/ownership': typeof AuthedManagepropertyOwnershipRoute
  '/manageproperty/priority': typeof AuthedManagepropertyPriorityRoute
  '/manageproperty/settings': typeof AuthedManagepropertySettingsRoute
  '/manageproperty/split-policy': typeof AuthedManagepropertySplitPolicyRoute
  '/manageproperty/structures': typeof AuthedManagepropertyStructuresRoute
  '/manageproperty/usergroups': typeof AuthedManagepropertyUsergroupsRoute
  '/manageproperty/users': typeof AuthedManagepropertyUsersRoute
  '/administrer': typeof AuthedAdministrerIndexRoute
  '/manageproperty': typeof AuthedManagepropertyIndexRoute
  '/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_authed/administrer': typeof AuthedAdministrerRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/expenses': typeof AuthedExpensesRoute
  '/_authed/handleliste': typeof AuthedHandlelisteRoute
  '/_authed/innstillinger': typeof AuthedInnstillingerRoute
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/manageproperty': typeof AuthedManagepropertyRouteWithChildren
  '/_authed/oppgaver': typeof AuthedOppgaverRoute
  '/_authed/oppgjor': typeof AuthedOppgjorRoute
  '/_authed/oversikt': typeof AuthedOversiktRoute
  '/_authed/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/_authed/planstay': typeof AuthedPlanstayRoute
  '/_authed/settlement': typeof AuthedSettlementRoute
  '/_authed/shoppinglist': typeof AuthedShoppinglistRoute
  '/_authed/todos': typeof AuthedTodosRoute
  '/_authed/usersettings': typeof AuthedUsersettingsRoute
  '/_authed/utlegg': typeof AuthedUtleggRoute
  '/_authed/vedlikehold': typeof AuthedVedlikeholdRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authed/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/_authed/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/_authed/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/_authed/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/_authed/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  '/_authed/administrer/info': typeof AuthedAdministrerInfoRoute
  '/_authed/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/_authed/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/_authed/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/_authed/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/_authed/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/_authed/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/_authed/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/_authed/manageproperty/contacts': typeof AuthedManagepropertyContactsRoute
  '/_authed/manageproperty/equipment': typeof AuthedManagepropertyEquipmentRoute
  '/_authed/manageproperty/info': typeof AuthedManagepropertyInfoRoute
  '/_authed/manageproperty/infrastructure': typeof AuthedManagepropertyInfrastructureRoute
  '/_authed/manageproperty/invites': typeof AuthedManagepropertyInvitesRoute
  '/_authed/manageproperty/ownership': typeof AuthedManagepropertyOwnershipRoute
  '/_authed/manageproperty/priority': typeof AuthedManagepropertyPriorityRoute
  '/_authed/manageproperty/settings': typeof AuthedManagepropertySettingsRoute
  '/_authed/manageproperty/split-policy': typeof AuthedManagepropertySplitPolicyRoute
  '/_authed/manageproperty/structures': typeof AuthedManagepropertyStructuresRoute
  '/_authed/manageproperty/usergroups': typeof AuthedManagepropertyUsergroupsRoute
  '/_authed/manageproperty/users': typeof AuthedManagepropertyUsersRoute
  '/_authed/administrer/': typeof AuthedAdministrerIndexRoute
  '/_authed/manageproperty/': typeof AuthedManagepropertyIndexRoute
  '/_authed/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/_authed/administrer/fordelingspolicy/': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrer'
    | '/dashboard'
    | '/expenses'
    | '/handleliste'
    | '/innstillinger'
    | '/maintenance'
    | '/manageproperty'
    | '/oppgaver'
    | '/oppgjor'
    | '/oversikt'
    | '/planleggopphold'
    | '/planstay'
    | '/settlement'
    | '/shoppinglist'
    | '/todos'
    | '/usersettings'
    | '/utlegg'
    | '/vedlikehold'
    | '/onboarding'
    | '/administrer/brukere'
    | '/administrer/brukergrupper'
    | '/administrer/bygninger'
    | '/administrer/eierskap'
    | '/administrer/fordelingspolicy'
    | '/administrer/info'
    | '/administrer/infrastruktur'
    | '/administrer/innstillinger'
    | '/administrer/invitasjoner'
    | '/administrer/kontakter'
    | '/administrer/prioritet'
    | '/administrer/utgiftskategorier'
    | '/administrer/utstyr'
    | '/manageproperty/contacts'
    | '/manageproperty/equipment'
    | '/manageproperty/info'
    | '/manageproperty/infrastructure'
    | '/manageproperty/invites'
    | '/manageproperty/ownership'
    | '/manageproperty/priority'
    | '/manageproperty/settings'
    | '/manageproperty/split-policy'
    | '/manageproperty/structures'
    | '/manageproperty/usergroups'
    | '/manageproperty/users'
    | '/administrer/'
    | '/manageproperty/'
    | '/administrer/fordelingspolicy/persondays'
    | '/administrer/fordelingspolicy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expenses'
    | '/handleliste'
    | '/innstillinger'
    | '/maintenance'
    | '/oppgaver'
    | '/oppgjor'
    | '/oversikt'
    | '/planleggopphold'
    | '/planstay'
    | '/settlement'
    | '/shoppinglist'
    | '/todos'
    | '/usersettings'
    | '/utlegg'
    | '/vedlikehold'
    | '/onboarding'
    | '/administrer/brukere'
    | '/administrer/brukergrupper'
    | '/administrer/bygninger'
    | '/administrer/eierskap'
    | '/administrer/info'
    | '/administrer/infrastruktur'
    | '/administrer/innstillinger'
    | '/administrer/invitasjoner'
    | '/administrer/kontakter'
    | '/administrer/prioritet'
    | '/administrer/utgiftskategorier'
    | '/administrer/utstyr'
    | '/manageproperty/contacts'
    | '/manageproperty/equipment'
    | '/manageproperty/info'
    | '/manageproperty/infrastructure'
    | '/manageproperty/invites'
    | '/manageproperty/ownership'
    | '/manageproperty/priority'
    | '/manageproperty/settings'
    | '/manageproperty/split-policy'
    | '/manageproperty/structures'
    | '/manageproperty/usergroups'
    | '/manageproperty/users'
    | '/administrer'
    | '/manageproperty'
    | '/administrer/fordelingspolicy/persondays'
    | '/administrer/fordelingspolicy'
  id:
    | '__root__'
    | '/_authed'
    | '/_marketing'
    | '/_onboarding'
    | '/_authed/administrer'
    | '/_authed/dashboard'
    | '/_authed/expenses'
    | '/_authed/handleliste'
    | '/_authed/innstillinger'
    | '/_authed/maintenance'
    | '/_authed/manageproperty'
    | '/_authed/oppgaver'
    | '/_authed/oppgjor'
    | '/_authed/oversikt'
    | '/_authed/planleggopphold'
    | '/_authed/planstay'
    | '/_authed/settlement'
    | '/_authed/shoppinglist'
    | '/_authed/todos'
    | '/_authed/usersettings'
    | '/_authed/utlegg'
    | '/_authed/vedlikehold'
    | '/_onboarding/onboarding'
    | '/_marketing/'
    | '/_authed/administrer/brukere'
    | '/_authed/administrer/brukergrupper'
    | '/_authed/administrer/bygninger'
    | '/_authed/administrer/eierskap'
    | '/_authed/administrer/fordelingspolicy'
    | '/_authed/administrer/info'
    | '/_authed/administrer/infrastruktur'
    | '/_authed/administrer/innstillinger'
    | '/_authed/administrer/invitasjoner'
    | '/_authed/administrer/kontakter'
    | '/_authed/administrer/prioritet'
    | '/_authed/administrer/utgiftskategorier'
    | '/_authed/administrer/utstyr'
    | '/_authed/manageproperty/contacts'
    | '/_authed/manageproperty/equipment'
    | '/_authed/manageproperty/info'
    | '/_authed/manageproperty/infrastructure'
    | '/_authed/manageproperty/invites'
    | '/_authed/manageproperty/ownership'
    | '/_authed/manageproperty/priority'
    | '/_authed/manageproperty/settings'
    | '/_authed/manageproperty/split-policy'
    | '/_authed/manageproperty/structures'
    | '/_authed/manageproperty/usergroups'
    | '/_authed/manageproperty/users'
    | '/_authed/administrer/'
    | '/_authed/manageproperty/'
    | '/_authed/administrer/fordelingspolicy/persondays'
    | '/_authed/administrer/fordelingspolicy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/vedlikehold': {
      id: '/_authed/vedlikehold'
      path: '/vedlikehold'
      fullPath: '/vedlikehold'
      preLoaderRoute: typeof AuthedVedlikeholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/utlegg': {
      id: '/_authed/utlegg'
      path: '/utlegg'
      fullPath: '/utlegg'
      preLoaderRoute: typeof AuthedUtleggRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/usersettings': {
      id: '/_authed/usersettings'
      path: '/usersettings'
      fullPath: '/usersettings'
      preLoaderRoute: typeof AuthedUsersettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todos': {
      id: '/_authed/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthedTodosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shoppinglist': {
      id: '/_authed/shoppinglist'
      path: '/shoppinglist'
      fullPath: '/shoppinglist'
      preLoaderRoute: typeof AuthedShoppinglistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settlement': {
      id: '/_authed/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthedSettlementRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planstay': {
      id: '/_authed/planstay'
      path: '/planstay'
      fullPath: '/planstay'
      preLoaderRoute: typeof AuthedPlanstayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planleggopphold': {
      id: '/_authed/planleggopphold'
      path: '/planleggopphold'
      fullPath: '/planleggopphold'
      preLoaderRoute: typeof AuthedPlanleggoppholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oversikt': {
      id: '/_authed/oversikt'
      path: '/oversikt'
      fullPath: '/oversikt'
      preLoaderRoute: typeof AuthedOversiktRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oppgjor': {
      id: '/_authed/oppgjor'
      path: '/oppgjor'
      fullPath: '/oppgjor'
      preLoaderRoute: typeof AuthedOppgjorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oppgaver': {
      id: '/_authed/oppgaver'
      path: '/oppgaver'
      fullPath: '/oppgaver'
      preLoaderRoute: typeof AuthedOppgaverRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manageproperty': {
      id: '/_authed/manageproperty'
      path: '/manageproperty'
      fullPath: '/manageproperty'
      preLoaderRoute: typeof AuthedManagepropertyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/innstillinger': {
      id: '/_authed/innstillinger'
      path: '/innstillinger'
      fullPath: '/innstillinger'
      preLoaderRoute: typeof AuthedInnstillingerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/handleliste': {
      id: '/_authed/handleliste'
      path: '/handleliste'
      fullPath: '/handleliste'
      preLoaderRoute: typeof AuthedHandlelisteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expenses': {
      id: '/_authed/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthedExpensesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/administrer': {
      id: '/_authed/administrer'
      path: '/administrer'
      fullPath: '/administrer'
      preLoaderRoute: typeof AuthedAdministrerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manageproperty/': {
      id: '/_authed/manageproperty/'
      path: '/'
      fullPath: '/manageproperty/'
      preLoaderRoute: typeof AuthedManagepropertyIndexRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/administrer/': {
      id: '/_authed/administrer/'
      path: '/'
      fullPath: '/administrer/'
      preLoaderRoute: typeof AuthedAdministrerIndexRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/manageproperty/users': {
      id: '/_authed/manageproperty/users'
      path: '/users'
      fullPath: '/manageproperty/users'
      preLoaderRoute: typeof AuthedManagepropertyUsersRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/usergroups': {
      id: '/_authed/manageproperty/usergroups'
      path: '/usergroups'
      fullPath: '/manageproperty/usergroups'
      preLoaderRoute: typeof AuthedManagepropertyUsergroupsRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/structures': {
      id: '/_authed/manageproperty/structures'
      path: '/structures'
      fullPath: '/manageproperty/structures'
      preLoaderRoute: typeof AuthedManagepropertyStructuresRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/split-policy': {
      id: '/_authed/manageproperty/split-policy'
      path: '/split-policy'
      fullPath: '/manageproperty/split-policy'
      preLoaderRoute: typeof AuthedManagepropertySplitPolicyRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/settings': {
      id: '/_authed/manageproperty/settings'
      path: '/settings'
      fullPath: '/manageproperty/settings'
      preLoaderRoute: typeof AuthedManagepropertySettingsRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/priority': {
      id: '/_authed/manageproperty/priority'
      path: '/priority'
      fullPath: '/manageproperty/priority'
      preLoaderRoute: typeof AuthedManagepropertyPriorityRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/ownership': {
      id: '/_authed/manageproperty/ownership'
      path: '/ownership'
      fullPath: '/manageproperty/ownership'
      preLoaderRoute: typeof AuthedManagepropertyOwnershipRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/invites': {
      id: '/_authed/manageproperty/invites'
      path: '/invites'
      fullPath: '/manageproperty/invites'
      preLoaderRoute: typeof AuthedManagepropertyInvitesRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/infrastructure': {
      id: '/_authed/manageproperty/infrastructure'
      path: '/infrastructure'
      fullPath: '/manageproperty/infrastructure'
      preLoaderRoute: typeof AuthedManagepropertyInfrastructureRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/info': {
      id: '/_authed/manageproperty/info'
      path: '/info'
      fullPath: '/manageproperty/info'
      preLoaderRoute: typeof AuthedManagepropertyInfoRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/equipment': {
      id: '/_authed/manageproperty/equipment'
      path: '/equipment'
      fullPath: '/manageproperty/equipment'
      preLoaderRoute: typeof AuthedManagepropertyEquipmentRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/manageproperty/contacts': {
      id: '/_authed/manageproperty/contacts'
      path: '/contacts'
      fullPath: '/manageproperty/contacts'
      preLoaderRoute: typeof AuthedManagepropertyContactsRouteImport
      parentRoute: typeof AuthedManagepropertyRoute
    }
    '/_authed/administrer/utstyr': {
      id: '/_authed/administrer/utstyr'
      path: '/utstyr'
      fullPath: '/administrer/utstyr'
      preLoaderRoute: typeof AuthedAdministrerUtstyrRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/utgiftskategorier': {
      id: '/_authed/administrer/utgiftskategorier'
      path: '/utgiftskategorier'
      fullPath: '/administrer/utgiftskategorier'
      preLoaderRoute: typeof AuthedAdministrerUtgiftskategorierRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/prioritet': {
      id: '/_authed/administrer/prioritet'
      path: '/prioritet'
      fullPath: '/administrer/prioritet'
      preLoaderRoute: typeof AuthedAdministrerPrioritetRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/kontakter': {
      id: '/_authed/administrer/kontakter'
      path: '/kontakter'
      fullPath: '/administrer/kontakter'
      preLoaderRoute: typeof AuthedAdministrerKontakterRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/invitasjoner': {
      id: '/_authed/administrer/invitasjoner'
      path: '/invitasjoner'
      fullPath: '/administrer/invitasjoner'
      preLoaderRoute: typeof AuthedAdministrerInvitasjonerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/innstillinger': {
      id: '/_authed/administrer/innstillinger'
      path: '/innstillinger'
      fullPath: '/administrer/innstillinger'
      preLoaderRoute: typeof AuthedAdministrerInnstillingerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/infrastruktur': {
      id: '/_authed/administrer/infrastruktur'
      path: '/infrastruktur'
      fullPath: '/administrer/infrastruktur'
      preLoaderRoute: typeof AuthedAdministrerInfrastrukturRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/info': {
      id: '/_authed/administrer/info'
      path: '/info'
      fullPath: '/administrer/info'
      preLoaderRoute: typeof AuthedAdministrerInfoRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/fordelingspolicy': {
      id: '/_authed/administrer/fordelingspolicy'
      path: '/fordelingspolicy'
      fullPath: '/administrer/fordelingspolicy'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/eierskap': {
      id: '/_authed/administrer/eierskap'
      path: '/eierskap'
      fullPath: '/administrer/eierskap'
      preLoaderRoute: typeof AuthedAdministrerEierskapRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/bygninger': {
      id: '/_authed/administrer/bygninger'
      path: '/bygninger'
      fullPath: '/administrer/bygninger'
      preLoaderRoute: typeof AuthedAdministrerBygningerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/brukergrupper': {
      id: '/_authed/administrer/brukergrupper'
      path: '/brukergrupper'
      fullPath: '/administrer/brukergrupper'
      preLoaderRoute: typeof AuthedAdministrerBrukergrupperRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/brukere': {
      id: '/_authed/administrer/brukere'
      path: '/brukere'
      fullPath: '/administrer/brukere'
      preLoaderRoute: typeof AuthedAdministrerBrukereRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/fordelingspolicy/': {
      id: '/_authed/administrer/fordelingspolicy/'
      path: '/'
      fullPath: '/administrer/fordelingspolicy/'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyIndexRouteImport
      parentRoute: typeof AuthedAdministrerFordelingspolicyRoute
    }
    '/_authed/administrer/fordelingspolicy/persondays': {
      id: '/_authed/administrer/fordelingspolicy/persondays'
      path: '/persondays'
      fullPath: '/administrer/fordelingspolicy/persondays'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyPersondaysRouteImport
      parentRoute: typeof AuthedAdministrerFordelingspolicyRoute
    }
  }
}

interface AuthedAdministrerFordelingspolicyRouteChildren {
  AuthedAdministrerFordelingspolicyPersondaysRoute: typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  AuthedAdministrerFordelingspolicyIndexRoute: typeof AuthedAdministrerFordelingspolicyIndexRoute
}

const AuthedAdministrerFordelingspolicyRouteChildren: AuthedAdministrerFordelingspolicyRouteChildren =
  {
    AuthedAdministrerFordelingspolicyPersondaysRoute:
      AuthedAdministrerFordelingspolicyPersondaysRoute,
    AuthedAdministrerFordelingspolicyIndexRoute:
      AuthedAdministrerFordelingspolicyIndexRoute,
  }

const AuthedAdministrerFordelingspolicyRouteWithChildren =
  AuthedAdministrerFordelingspolicyRoute._addFileChildren(
    AuthedAdministrerFordelingspolicyRouteChildren,
  )

interface AuthedAdministrerRouteChildren {
  AuthedAdministrerBrukereRoute: typeof AuthedAdministrerBrukereRoute
  AuthedAdministrerBrukergrupperRoute: typeof AuthedAdministrerBrukergrupperRoute
  AuthedAdministrerBygningerRoute: typeof AuthedAdministrerBygningerRoute
  AuthedAdministrerEierskapRoute: typeof AuthedAdministrerEierskapRoute
  AuthedAdministrerFordelingspolicyRoute: typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  AuthedAdministrerInfoRoute: typeof AuthedAdministrerInfoRoute
  AuthedAdministrerInfrastrukturRoute: typeof AuthedAdministrerInfrastrukturRoute
  AuthedAdministrerInnstillingerRoute: typeof AuthedAdministrerInnstillingerRoute
  AuthedAdministrerInvitasjonerRoute: typeof AuthedAdministrerInvitasjonerRoute
  AuthedAdministrerKontakterRoute: typeof AuthedAdministrerKontakterRoute
  AuthedAdministrerPrioritetRoute: typeof AuthedAdministrerPrioritetRoute
  AuthedAdministrerUtgiftskategorierRoute: typeof AuthedAdministrerUtgiftskategorierRoute
  AuthedAdministrerUtstyrRoute: typeof AuthedAdministrerUtstyrRoute
  AuthedAdministrerIndexRoute: typeof AuthedAdministrerIndexRoute
}

const AuthedAdministrerRouteChildren: AuthedAdministrerRouteChildren = {
  AuthedAdministrerBrukereRoute: AuthedAdministrerBrukereRoute,
  AuthedAdministrerBrukergrupperRoute: AuthedAdministrerBrukergrupperRoute,
  AuthedAdministrerBygningerRoute: AuthedAdministrerBygningerRoute,
  AuthedAdministrerEierskapRoute: AuthedAdministrerEierskapRoute,
  AuthedAdministrerFordelingspolicyRoute:
    AuthedAdministrerFordelingspolicyRouteWithChildren,
  AuthedAdministrerInfoRoute: AuthedAdministrerInfoRoute,
  AuthedAdministrerInfrastrukturRoute: AuthedAdministrerInfrastrukturRoute,
  AuthedAdministrerInnstillingerRoute: AuthedAdministrerInnstillingerRoute,
  AuthedAdministrerInvitasjonerRoute: AuthedAdministrerInvitasjonerRoute,
  AuthedAdministrerKontakterRoute: AuthedAdministrerKontakterRoute,
  AuthedAdministrerPrioritetRoute: AuthedAdministrerPrioritetRoute,
  AuthedAdministrerUtgiftskategorierRoute:
    AuthedAdministrerUtgiftskategorierRoute,
  AuthedAdministrerUtstyrRoute: AuthedAdministrerUtstyrRoute,
  AuthedAdministrerIndexRoute: AuthedAdministrerIndexRoute,
}

const AuthedAdministrerRouteWithChildren =
  AuthedAdministrerRoute._addFileChildren(AuthedAdministrerRouteChildren)

interface AuthedManagepropertyRouteChildren {
  AuthedManagepropertyContactsRoute: typeof AuthedManagepropertyContactsRoute
  AuthedManagepropertyEquipmentRoute: typeof AuthedManagepropertyEquipmentRoute
  AuthedManagepropertyInfoRoute: typeof AuthedManagepropertyInfoRoute
  AuthedManagepropertyInfrastructureRoute: typeof AuthedManagepropertyInfrastructureRoute
  AuthedManagepropertyInvitesRoute: typeof AuthedManagepropertyInvitesRoute
  AuthedManagepropertyOwnershipRoute: typeof AuthedManagepropertyOwnershipRoute
  AuthedManagepropertyPriorityRoute: typeof AuthedManagepropertyPriorityRoute
  AuthedManagepropertySettingsRoute: typeof AuthedManagepropertySettingsRoute
  AuthedManagepropertySplitPolicyRoute: typeof AuthedManagepropertySplitPolicyRoute
  AuthedManagepropertyStructuresRoute: typeof AuthedManagepropertyStructuresRoute
  AuthedManagepropertyUsergroupsRoute: typeof AuthedManagepropertyUsergroupsRoute
  AuthedManagepropertyUsersRoute: typeof AuthedManagepropertyUsersRoute
  AuthedManagepropertyIndexRoute: typeof AuthedManagepropertyIndexRoute
}

const AuthedManagepropertyRouteChildren: AuthedManagepropertyRouteChildren = {
  AuthedManagepropertyContactsRoute: AuthedManagepropertyContactsRoute,
  AuthedManagepropertyEquipmentRoute: AuthedManagepropertyEquipmentRoute,
  AuthedManagepropertyInfoRoute: AuthedManagepropertyInfoRoute,
  AuthedManagepropertyInfrastructureRoute:
    AuthedManagepropertyInfrastructureRoute,
  AuthedManagepropertyInvitesRoute: AuthedManagepropertyInvitesRoute,
  AuthedManagepropertyOwnershipRoute: AuthedManagepropertyOwnershipRoute,
  AuthedManagepropertyPriorityRoute: AuthedManagepropertyPriorityRoute,
  AuthedManagepropertySettingsRoute: AuthedManagepropertySettingsRoute,
  AuthedManagepropertySplitPolicyRoute: AuthedManagepropertySplitPolicyRoute,
  AuthedManagepropertyStructuresRoute: AuthedManagepropertyStructuresRoute,
  AuthedManagepropertyUsergroupsRoute: AuthedManagepropertyUsergroupsRoute,
  AuthedManagepropertyUsersRoute: AuthedManagepropertyUsersRoute,
  AuthedManagepropertyIndexRoute: AuthedManagepropertyIndexRoute,
}

const AuthedManagepropertyRouteWithChildren =
  AuthedManagepropertyRoute._addFileChildren(AuthedManagepropertyRouteChildren)

interface AuthedRouteChildren {
  AuthedAdministrerRoute: typeof AuthedAdministrerRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedExpensesRoute: typeof AuthedExpensesRoute
  AuthedHandlelisteRoute: typeof AuthedHandlelisteRoute
  AuthedInnstillingerRoute: typeof AuthedInnstillingerRoute
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedManagepropertyRoute: typeof AuthedManagepropertyRouteWithChildren
  AuthedOppgaverRoute: typeof AuthedOppgaverRoute
  AuthedOppgjorRoute: typeof AuthedOppgjorRoute
  AuthedOversiktRoute: typeof AuthedOversiktRoute
  AuthedPlanleggoppholdRoute: typeof AuthedPlanleggoppholdRoute
  AuthedPlanstayRoute: typeof AuthedPlanstayRoute
  AuthedSettlementRoute: typeof AuthedSettlementRoute
  AuthedShoppinglistRoute: typeof AuthedShoppinglistRoute
  AuthedTodosRoute: typeof AuthedTodosRoute
  AuthedUsersettingsRoute: typeof AuthedUsersettingsRoute
  AuthedUtleggRoute: typeof AuthedUtleggRoute
  AuthedVedlikeholdRoute: typeof AuthedVedlikeholdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdministrerRoute: AuthedAdministrerRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedExpensesRoute: AuthedExpensesRoute,
  AuthedHandlelisteRoute: AuthedHandlelisteRoute,
  AuthedInnstillingerRoute: AuthedInnstillingerRoute,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedManagepropertyRoute: AuthedManagepropertyRouteWithChildren,
  AuthedOppgaverRoute: AuthedOppgaverRoute,
  AuthedOppgjorRoute: AuthedOppgjorRoute,
  AuthedOversiktRoute: AuthedOversiktRoute,
  AuthedPlanleggoppholdRoute: AuthedPlanleggoppholdRoute,
  AuthedPlanstayRoute: AuthedPlanstayRoute,
  AuthedSettlementRoute: AuthedSettlementRoute,
  AuthedShoppinglistRoute: AuthedShoppinglistRoute,
  AuthedTodosRoute: AuthedTodosRoute,
  AuthedUsersettingsRoute: AuthedUsersettingsRoute,
  AuthedUtleggRoute: AuthedUtleggRoute,
  AuthedVedlikeholdRoute: AuthedVedlikeholdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
