/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as AuthedVedlikeholdRouteImport } from './routes/_authed/vedlikehold'
import { Route as AuthedUtleggRouteImport } from './routes/_authed/utlegg'
import { Route as AuthedPlanleggoppholdRouteImport } from './routes/_authed/planleggopphold'
import { Route as AuthedOversiktRouteImport } from './routes/_authed/oversikt'
import { Route as AuthedOppgjorRouteImport } from './routes/_authed/oppgjor'
import { Route as AuthedOppgaverRouteImport } from './routes/_authed/oppgaver'
import { Route as AuthedKontakterRouteImport } from './routes/_authed/kontakter'
import { Route as AuthedInventarRouteImport } from './routes/_authed/inventar'
import { Route as AuthedInnstillingerRouteImport } from './routes/_authed/innstillinger'
import { Route as AuthedHandlelisteRouteImport } from './routes/_authed/handleliste'
import { Route as AuthedAdministrerRouteImport } from './routes/_authed/administrer'
import { Route as AuthedAdministrerIndexRouteImport } from './routes/_authed/administrer/index'
import { Route as AuthedAdministrerUtstyrRouteImport } from './routes/_authed/administrer/utstyr'
import { Route as AuthedAdministrerUtgiftskategorierRouteImport } from './routes/_authed/administrer/utgiftskategorier'
import { Route as AuthedAdministrerSesongerRouteImport } from './routes/_authed/administrer/sesonger'
import { Route as AuthedAdministrerPrioritetRouteImport } from './routes/_authed/administrer/prioritet'
import { Route as AuthedAdministrerKontakterRouteImport } from './routes/_authed/administrer/kontakter'
import { Route as AuthedAdministrerInvitasjonerRouteImport } from './routes/_authed/administrer/invitasjoner'
import { Route as AuthedAdministrerInventarkategorierRouteImport } from './routes/_authed/administrer/inventarkategorier'
import { Route as AuthedAdministrerInnstillingerRouteImport } from './routes/_authed/administrer/innstillinger'
import { Route as AuthedAdministrerInfrastrukturRouteImport } from './routes/_authed/administrer/infrastruktur'
import { Route as AuthedAdministrerInfoRouteImport } from './routes/_authed/administrer/info'
import { Route as AuthedAdministrerFordelingspolicyRouteImport } from './routes/_authed/administrer/fordelingspolicy'
import { Route as AuthedAdministrerEierskapRouteImport } from './routes/_authed/administrer/eierskap'
import { Route as AuthedAdministrerBygningerRouteImport } from './routes/_authed/administrer/bygninger'
import { Route as AuthedAdministrerBrukergrupperRouteImport } from './routes/_authed/administrer/brukergrupper'
import { Route as AuthedAdministrerBrukereRouteImport } from './routes/_authed/administrer/brukere'
import { Route as AuthedAdministrerFordelingspolicyIndexRouteImport } from './routes/_authed/administrer/fordelingspolicy/index'
import { Route as AuthedAdministrerFordelingspolicyPersondaysRouteImport } from './routes/_authed/administrer/fordelingspolicy/persondays'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedVedlikeholdRoute = AuthedVedlikeholdRouteImport.update({
  id: '/vedlikehold',
  path: '/vedlikehold',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUtleggRoute = AuthedUtleggRouteImport.update({
  id: '/utlegg',
  path: '/utlegg',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanleggoppholdRoute = AuthedPlanleggoppholdRouteImport.update({
  id: '/planleggopphold',
  path: '/planleggopphold',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOversiktRoute = AuthedOversiktRouteImport.update({
  id: '/oversikt',
  path: '/oversikt',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOppgjorRoute = AuthedOppgjorRouteImport.update({
  id: '/oppgjor',
  path: '/oppgjor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOppgaverRoute = AuthedOppgaverRouteImport.update({
  id: '/oppgaver',
  path: '/oppgaver',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKontakterRoute = AuthedKontakterRouteImport.update({
  id: '/kontakter',
  path: '/kontakter',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventarRoute = AuthedInventarRouteImport.update({
  id: '/inventar',
  path: '/inventar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInnstillingerRoute = AuthedInnstillingerRouteImport.update({
  id: '/innstillinger',
  path: '/innstillinger',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHandlelisteRoute = AuthedHandlelisteRouteImport.update({
  id: '/handleliste',
  path: '/handleliste',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdministrerRoute = AuthedAdministrerRouteImport.update({
  id: '/administrer',
  path: '/administrer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdministrerIndexRoute = AuthedAdministrerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedAdministrerUtstyrRoute = AuthedAdministrerUtstyrRouteImport.update({
  id: '/utstyr',
  path: '/utstyr',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedAdministrerUtgiftskategorierRoute =
  AuthedAdministrerUtgiftskategorierRouteImport.update({
    id: '/utgiftskategorier',
    path: '/utgiftskategorier',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerSesongerRoute =
  AuthedAdministrerSesongerRouteImport.update({
    id: '/sesonger',
    path: '/sesonger',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerPrioritetRoute =
  AuthedAdministrerPrioritetRouteImport.update({
    id: '/prioritet',
    path: '/prioritet',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerKontakterRoute =
  AuthedAdministrerKontakterRouteImport.update({
    id: '/kontakter',
    path: '/kontakter',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInvitasjonerRoute =
  AuthedAdministrerInvitasjonerRouteImport.update({
    id: '/invitasjoner',
    path: '/invitasjoner',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInventarkategorierRoute =
  AuthedAdministrerInventarkategorierRouteImport.update({
    id: '/inventarkategorier',
    path: '/inventarkategorier',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInnstillingerRoute =
  AuthedAdministrerInnstillingerRouteImport.update({
    id: '/innstillinger',
    path: '/innstillinger',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInfrastrukturRoute =
  AuthedAdministrerInfrastrukturRouteImport.update({
    id: '/infrastruktur',
    path: '/infrastruktur',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerInfoRoute = AuthedAdministrerInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthedAdministrerRoute,
} as any)
const AuthedAdministrerFordelingspolicyRoute =
  AuthedAdministrerFordelingspolicyRouteImport.update({
    id: '/fordelingspolicy',
    path: '/fordelingspolicy',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerEierskapRoute =
  AuthedAdministrerEierskapRouteImport.update({
    id: '/eierskap',
    path: '/eierskap',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBygningerRoute =
  AuthedAdministrerBygningerRouteImport.update({
    id: '/bygninger',
    path: '/bygninger',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBrukergrupperRoute =
  AuthedAdministrerBrukergrupperRouteImport.update({
    id: '/brukergrupper',
    path: '/brukergrupper',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerBrukereRoute =
  AuthedAdministrerBrukereRouteImport.update({
    id: '/brukere',
    path: '/brukere',
    getParentRoute: () => AuthedAdministrerRoute,
  } as any)
const AuthedAdministrerFordelingspolicyIndexRoute =
  AuthedAdministrerFordelingspolicyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdministrerFordelingspolicyRoute,
  } as any)
const AuthedAdministrerFordelingspolicyPersondaysRoute =
  AuthedAdministrerFordelingspolicyPersondaysRouteImport.update({
    id: '/persondays',
    path: '/persondays',
    getParentRoute: () => AuthedAdministrerFordelingspolicyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/administrer': typeof AuthedAdministrerRouteWithChildren
  '/handleliste': typeof AuthedHandlelisteRoute
  '/innstillinger': typeof AuthedInnstillingerRoute
  '/inventar': typeof AuthedInventarRoute
  '/kontakter': typeof AuthedKontakterRoute
  '/oppgaver': typeof AuthedOppgaverRoute
  '/oppgjor': typeof AuthedOppgjorRoute
  '/oversikt': typeof AuthedOversiktRoute
  '/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/utlegg': typeof AuthedUtleggRoute
  '/vedlikehold': typeof AuthedVedlikeholdRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  '/administrer/info': typeof AuthedAdministrerInfoRoute
  '/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/administrer/inventarkategorier': typeof AuthedAdministrerInventarkategorierRoute
  '/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/administrer/sesonger': typeof AuthedAdministrerSesongerRoute
  '/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/administrer/': typeof AuthedAdministrerIndexRoute
  '/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/administrer/fordelingspolicy/': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/handleliste': typeof AuthedHandlelisteRoute
  '/innstillinger': typeof AuthedInnstillingerRoute
  '/inventar': typeof AuthedInventarRoute
  '/kontakter': typeof AuthedKontakterRoute
  '/oppgaver': typeof AuthedOppgaverRoute
  '/oppgjor': typeof AuthedOppgjorRoute
  '/oversikt': typeof AuthedOversiktRoute
  '/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/utlegg': typeof AuthedUtleggRoute
  '/vedlikehold': typeof AuthedVedlikeholdRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/administrer/info': typeof AuthedAdministrerInfoRoute
  '/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/administrer/inventarkategorier': typeof AuthedAdministrerInventarkategorierRoute
  '/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/administrer/sesonger': typeof AuthedAdministrerSesongerRoute
  '/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/administrer': typeof AuthedAdministrerIndexRoute
  '/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_authed/administrer': typeof AuthedAdministrerRouteWithChildren
  '/_authed/handleliste': typeof AuthedHandlelisteRoute
  '/_authed/innstillinger': typeof AuthedInnstillingerRoute
  '/_authed/inventar': typeof AuthedInventarRoute
  '/_authed/kontakter': typeof AuthedKontakterRoute
  '/_authed/oppgaver': typeof AuthedOppgaverRoute
  '/_authed/oppgjor': typeof AuthedOppgjorRoute
  '/_authed/oversikt': typeof AuthedOversiktRoute
  '/_authed/planleggopphold': typeof AuthedPlanleggoppholdRoute
  '/_authed/utlegg': typeof AuthedUtleggRoute
  '/_authed/vedlikehold': typeof AuthedVedlikeholdRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authed/administrer/brukere': typeof AuthedAdministrerBrukereRoute
  '/_authed/administrer/brukergrupper': typeof AuthedAdministrerBrukergrupperRoute
  '/_authed/administrer/bygninger': typeof AuthedAdministrerBygningerRoute
  '/_authed/administrer/eierskap': typeof AuthedAdministrerEierskapRoute
  '/_authed/administrer/fordelingspolicy': typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  '/_authed/administrer/info': typeof AuthedAdministrerInfoRoute
  '/_authed/administrer/infrastruktur': typeof AuthedAdministrerInfrastrukturRoute
  '/_authed/administrer/innstillinger': typeof AuthedAdministrerInnstillingerRoute
  '/_authed/administrer/inventarkategorier': typeof AuthedAdministrerInventarkategorierRoute
  '/_authed/administrer/invitasjoner': typeof AuthedAdministrerInvitasjonerRoute
  '/_authed/administrer/kontakter': typeof AuthedAdministrerKontakterRoute
  '/_authed/administrer/prioritet': typeof AuthedAdministrerPrioritetRoute
  '/_authed/administrer/sesonger': typeof AuthedAdministrerSesongerRoute
  '/_authed/administrer/utgiftskategorier': typeof AuthedAdministrerUtgiftskategorierRoute
  '/_authed/administrer/utstyr': typeof AuthedAdministrerUtstyrRoute
  '/_authed/administrer/': typeof AuthedAdministrerIndexRoute
  '/_authed/administrer/fordelingspolicy/persondays': typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  '/_authed/administrer/fordelingspolicy/': typeof AuthedAdministrerFordelingspolicyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrer'
    | '/handleliste'
    | '/innstillinger'
    | '/inventar'
    | '/kontakter'
    | '/oppgaver'
    | '/oppgjor'
    | '/oversikt'
    | '/planleggopphold'
    | '/utlegg'
    | '/vedlikehold'
    | '/onboarding'
    | '/administrer/brukere'
    | '/administrer/brukergrupper'
    | '/administrer/bygninger'
    | '/administrer/eierskap'
    | '/administrer/fordelingspolicy'
    | '/administrer/info'
    | '/administrer/infrastruktur'
    | '/administrer/innstillinger'
    | '/administrer/inventarkategorier'
    | '/administrer/invitasjoner'
    | '/administrer/kontakter'
    | '/administrer/prioritet'
    | '/administrer/sesonger'
    | '/administrer/utgiftskategorier'
    | '/administrer/utstyr'
    | '/administrer/'
    | '/administrer/fordelingspolicy/persondays'
    | '/administrer/fordelingspolicy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handleliste'
    | '/innstillinger'
    | '/inventar'
    | '/kontakter'
    | '/oppgaver'
    | '/oppgjor'
    | '/oversikt'
    | '/planleggopphold'
    | '/utlegg'
    | '/vedlikehold'
    | '/onboarding'
    | '/administrer/brukere'
    | '/administrer/brukergrupper'
    | '/administrer/bygninger'
    | '/administrer/eierskap'
    | '/administrer/info'
    | '/administrer/infrastruktur'
    | '/administrer/innstillinger'
    | '/administrer/inventarkategorier'
    | '/administrer/invitasjoner'
    | '/administrer/kontakter'
    | '/administrer/prioritet'
    | '/administrer/sesonger'
    | '/administrer/utgiftskategorier'
    | '/administrer/utstyr'
    | '/administrer'
    | '/administrer/fordelingspolicy/persondays'
    | '/administrer/fordelingspolicy'
  id:
    | '__root__'
    | '/_authed'
    | '/_marketing'
    | '/_onboarding'
    | '/_authed/administrer'
    | '/_authed/handleliste'
    | '/_authed/innstillinger'
    | '/_authed/inventar'
    | '/_authed/kontakter'
    | '/_authed/oppgaver'
    | '/_authed/oppgjor'
    | '/_authed/oversikt'
    | '/_authed/planleggopphold'
    | '/_authed/utlegg'
    | '/_authed/vedlikehold'
    | '/_onboarding/onboarding'
    | '/_marketing/'
    | '/_authed/administrer/brukere'
    | '/_authed/administrer/brukergrupper'
    | '/_authed/administrer/bygninger'
    | '/_authed/administrer/eierskap'
    | '/_authed/administrer/fordelingspolicy'
    | '/_authed/administrer/info'
    | '/_authed/administrer/infrastruktur'
    | '/_authed/administrer/innstillinger'
    | '/_authed/administrer/inventarkategorier'
    | '/_authed/administrer/invitasjoner'
    | '/_authed/administrer/kontakter'
    | '/_authed/administrer/prioritet'
    | '/_authed/administrer/sesonger'
    | '/_authed/administrer/utgiftskategorier'
    | '/_authed/administrer/utstyr'
    | '/_authed/administrer/'
    | '/_authed/administrer/fordelingspolicy/persondays'
    | '/_authed/administrer/fordelingspolicy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/vedlikehold': {
      id: '/_authed/vedlikehold'
      path: '/vedlikehold'
      fullPath: '/vedlikehold'
      preLoaderRoute: typeof AuthedVedlikeholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/utlegg': {
      id: '/_authed/utlegg'
      path: '/utlegg'
      fullPath: '/utlegg'
      preLoaderRoute: typeof AuthedUtleggRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planleggopphold': {
      id: '/_authed/planleggopphold'
      path: '/planleggopphold'
      fullPath: '/planleggopphold'
      preLoaderRoute: typeof AuthedPlanleggoppholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oversikt': {
      id: '/_authed/oversikt'
      path: '/oversikt'
      fullPath: '/oversikt'
      preLoaderRoute: typeof AuthedOversiktRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oppgjor': {
      id: '/_authed/oppgjor'
      path: '/oppgjor'
      fullPath: '/oppgjor'
      preLoaderRoute: typeof AuthedOppgjorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oppgaver': {
      id: '/_authed/oppgaver'
      path: '/oppgaver'
      fullPath: '/oppgaver'
      preLoaderRoute: typeof AuthedOppgaverRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kontakter': {
      id: '/_authed/kontakter'
      path: '/kontakter'
      fullPath: '/kontakter'
      preLoaderRoute: typeof AuthedKontakterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventar': {
      id: '/_authed/inventar'
      path: '/inventar'
      fullPath: '/inventar'
      preLoaderRoute: typeof AuthedInventarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/innstillinger': {
      id: '/_authed/innstillinger'
      path: '/innstillinger'
      fullPath: '/innstillinger'
      preLoaderRoute: typeof AuthedInnstillingerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/handleliste': {
      id: '/_authed/handleliste'
      path: '/handleliste'
      fullPath: '/handleliste'
      preLoaderRoute: typeof AuthedHandlelisteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/administrer': {
      id: '/_authed/administrer'
      path: '/administrer'
      fullPath: '/administrer'
      preLoaderRoute: typeof AuthedAdministrerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/administrer/': {
      id: '/_authed/administrer/'
      path: '/'
      fullPath: '/administrer/'
      preLoaderRoute: typeof AuthedAdministrerIndexRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/utstyr': {
      id: '/_authed/administrer/utstyr'
      path: '/utstyr'
      fullPath: '/administrer/utstyr'
      preLoaderRoute: typeof AuthedAdministrerUtstyrRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/utgiftskategorier': {
      id: '/_authed/administrer/utgiftskategorier'
      path: '/utgiftskategorier'
      fullPath: '/administrer/utgiftskategorier'
      preLoaderRoute: typeof AuthedAdministrerUtgiftskategorierRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/sesonger': {
      id: '/_authed/administrer/sesonger'
      path: '/sesonger'
      fullPath: '/administrer/sesonger'
      preLoaderRoute: typeof AuthedAdministrerSesongerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/prioritet': {
      id: '/_authed/administrer/prioritet'
      path: '/prioritet'
      fullPath: '/administrer/prioritet'
      preLoaderRoute: typeof AuthedAdministrerPrioritetRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/kontakter': {
      id: '/_authed/administrer/kontakter'
      path: '/kontakter'
      fullPath: '/administrer/kontakter'
      preLoaderRoute: typeof AuthedAdministrerKontakterRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/invitasjoner': {
      id: '/_authed/administrer/invitasjoner'
      path: '/invitasjoner'
      fullPath: '/administrer/invitasjoner'
      preLoaderRoute: typeof AuthedAdministrerInvitasjonerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/inventarkategorier': {
      id: '/_authed/administrer/inventarkategorier'
      path: '/inventarkategorier'
      fullPath: '/administrer/inventarkategorier'
      preLoaderRoute: typeof AuthedAdministrerInventarkategorierRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/innstillinger': {
      id: '/_authed/administrer/innstillinger'
      path: '/innstillinger'
      fullPath: '/administrer/innstillinger'
      preLoaderRoute: typeof AuthedAdministrerInnstillingerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/infrastruktur': {
      id: '/_authed/administrer/infrastruktur'
      path: '/infrastruktur'
      fullPath: '/administrer/infrastruktur'
      preLoaderRoute: typeof AuthedAdministrerInfrastrukturRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/info': {
      id: '/_authed/administrer/info'
      path: '/info'
      fullPath: '/administrer/info'
      preLoaderRoute: typeof AuthedAdministrerInfoRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/fordelingspolicy': {
      id: '/_authed/administrer/fordelingspolicy'
      path: '/fordelingspolicy'
      fullPath: '/administrer/fordelingspolicy'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/eierskap': {
      id: '/_authed/administrer/eierskap'
      path: '/eierskap'
      fullPath: '/administrer/eierskap'
      preLoaderRoute: typeof AuthedAdministrerEierskapRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/bygninger': {
      id: '/_authed/administrer/bygninger'
      path: '/bygninger'
      fullPath: '/administrer/bygninger'
      preLoaderRoute: typeof AuthedAdministrerBygningerRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/brukergrupper': {
      id: '/_authed/administrer/brukergrupper'
      path: '/brukergrupper'
      fullPath: '/administrer/brukergrupper'
      preLoaderRoute: typeof AuthedAdministrerBrukergrupperRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/brukere': {
      id: '/_authed/administrer/brukere'
      path: '/brukere'
      fullPath: '/administrer/brukere'
      preLoaderRoute: typeof AuthedAdministrerBrukereRouteImport
      parentRoute: typeof AuthedAdministrerRoute
    }
    '/_authed/administrer/fordelingspolicy/': {
      id: '/_authed/administrer/fordelingspolicy/'
      path: '/'
      fullPath: '/administrer/fordelingspolicy/'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyIndexRouteImport
      parentRoute: typeof AuthedAdministrerFordelingspolicyRoute
    }
    '/_authed/administrer/fordelingspolicy/persondays': {
      id: '/_authed/administrer/fordelingspolicy/persondays'
      path: '/persondays'
      fullPath: '/administrer/fordelingspolicy/persondays'
      preLoaderRoute: typeof AuthedAdministrerFordelingspolicyPersondaysRouteImport
      parentRoute: typeof AuthedAdministrerFordelingspolicyRoute
    }
  }
}

interface AuthedAdministrerFordelingspolicyRouteChildren {
  AuthedAdministrerFordelingspolicyPersondaysRoute: typeof AuthedAdministrerFordelingspolicyPersondaysRoute
  AuthedAdministrerFordelingspolicyIndexRoute: typeof AuthedAdministrerFordelingspolicyIndexRoute
}

const AuthedAdministrerFordelingspolicyRouteChildren: AuthedAdministrerFordelingspolicyRouteChildren =
  {
    AuthedAdministrerFordelingspolicyPersondaysRoute:
      AuthedAdministrerFordelingspolicyPersondaysRoute,
    AuthedAdministrerFordelingspolicyIndexRoute:
      AuthedAdministrerFordelingspolicyIndexRoute,
  }

const AuthedAdministrerFordelingspolicyRouteWithChildren =
  AuthedAdministrerFordelingspolicyRoute._addFileChildren(
    AuthedAdministrerFordelingspolicyRouteChildren,
  )

interface AuthedAdministrerRouteChildren {
  AuthedAdministrerBrukereRoute: typeof AuthedAdministrerBrukereRoute
  AuthedAdministrerBrukergrupperRoute: typeof AuthedAdministrerBrukergrupperRoute
  AuthedAdministrerBygningerRoute: typeof AuthedAdministrerBygningerRoute
  AuthedAdministrerEierskapRoute: typeof AuthedAdministrerEierskapRoute
  AuthedAdministrerFordelingspolicyRoute: typeof AuthedAdministrerFordelingspolicyRouteWithChildren
  AuthedAdministrerInfoRoute: typeof AuthedAdministrerInfoRoute
  AuthedAdministrerInfrastrukturRoute: typeof AuthedAdministrerInfrastrukturRoute
  AuthedAdministrerInnstillingerRoute: typeof AuthedAdministrerInnstillingerRoute
  AuthedAdministrerInventarkategorierRoute: typeof AuthedAdministrerInventarkategorierRoute
  AuthedAdministrerInvitasjonerRoute: typeof AuthedAdministrerInvitasjonerRoute
  AuthedAdministrerKontakterRoute: typeof AuthedAdministrerKontakterRoute
  AuthedAdministrerPrioritetRoute: typeof AuthedAdministrerPrioritetRoute
  AuthedAdministrerSesongerRoute: typeof AuthedAdministrerSesongerRoute
  AuthedAdministrerUtgiftskategorierRoute: typeof AuthedAdministrerUtgiftskategorierRoute
  AuthedAdministrerUtstyrRoute: typeof AuthedAdministrerUtstyrRoute
  AuthedAdministrerIndexRoute: typeof AuthedAdministrerIndexRoute
}

const AuthedAdministrerRouteChildren: AuthedAdministrerRouteChildren = {
  AuthedAdministrerBrukereRoute: AuthedAdministrerBrukereRoute,
  AuthedAdministrerBrukergrupperRoute: AuthedAdministrerBrukergrupperRoute,
  AuthedAdministrerBygningerRoute: AuthedAdministrerBygningerRoute,
  AuthedAdministrerEierskapRoute: AuthedAdministrerEierskapRoute,
  AuthedAdministrerFordelingspolicyRoute:
    AuthedAdministrerFordelingspolicyRouteWithChildren,
  AuthedAdministrerInfoRoute: AuthedAdministrerInfoRoute,
  AuthedAdministrerInfrastrukturRoute: AuthedAdministrerInfrastrukturRoute,
  AuthedAdministrerInnstillingerRoute: AuthedAdministrerInnstillingerRoute,
  AuthedAdministrerInventarkategorierRoute:
    AuthedAdministrerInventarkategorierRoute,
  AuthedAdministrerInvitasjonerRoute: AuthedAdministrerInvitasjonerRoute,
  AuthedAdministrerKontakterRoute: AuthedAdministrerKontakterRoute,
  AuthedAdministrerPrioritetRoute: AuthedAdministrerPrioritetRoute,
  AuthedAdministrerSesongerRoute: AuthedAdministrerSesongerRoute,
  AuthedAdministrerUtgiftskategorierRoute:
    AuthedAdministrerUtgiftskategorierRoute,
  AuthedAdministrerUtstyrRoute: AuthedAdministrerUtstyrRoute,
  AuthedAdministrerIndexRoute: AuthedAdministrerIndexRoute,
}

const AuthedAdministrerRouteWithChildren =
  AuthedAdministrerRoute._addFileChildren(AuthedAdministrerRouteChildren)

interface AuthedRouteChildren {
  AuthedAdministrerRoute: typeof AuthedAdministrerRouteWithChildren
  AuthedHandlelisteRoute: typeof AuthedHandlelisteRoute
  AuthedInnstillingerRoute: typeof AuthedInnstillingerRoute
  AuthedInventarRoute: typeof AuthedInventarRoute
  AuthedKontakterRoute: typeof AuthedKontakterRoute
  AuthedOppgaverRoute: typeof AuthedOppgaverRoute
  AuthedOppgjorRoute: typeof AuthedOppgjorRoute
  AuthedOversiktRoute: typeof AuthedOversiktRoute
  AuthedPlanleggoppholdRoute: typeof AuthedPlanleggoppholdRoute
  AuthedUtleggRoute: typeof AuthedUtleggRoute
  AuthedVedlikeholdRoute: typeof AuthedVedlikeholdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdministrerRoute: AuthedAdministrerRouteWithChildren,
  AuthedHandlelisteRoute: AuthedHandlelisteRoute,
  AuthedInnstillingerRoute: AuthedInnstillingerRoute,
  AuthedInventarRoute: AuthedInventarRoute,
  AuthedKontakterRoute: AuthedKontakterRoute,
  AuthedOppgaverRoute: AuthedOppgaverRoute,
  AuthedOppgjorRoute: AuthedOppgjorRoute,
  AuthedOversiktRoute: AuthedOversiktRoute,
  AuthedPlanleggoppholdRoute: AuthedPlanleggoppholdRoute,
  AuthedUtleggRoute: AuthedUtleggRoute,
  AuthedVedlikeholdRoute: AuthedVedlikeholdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
